export const PREFECTURE_LIST_REQUEST = "PREFECTURE_LIST_REQUEST";
export const PREFECTURE_LIST_SUCCESS = "PREFECTURE_LIST_SUCCESS";
export const PREFECTURE_LIST_FAIL_SERVER = "PREFECTURE_LIST_FAIL_SERVER";
export const PREFECTURE_LIST_FAIL_USER = "PREFECTURE_LIST_FAIL_USER";

export const ADD_TO_POPULATION_LIST_SUCCESS = "ADD_TO_POPULATION_LIST_SUCCESS";
export const ADD_TO_POPULATION_LIST_FAIL = "ADD_TO_POPULATION_LIST_FAIL";
export const REMOVE_TO_POPULATION_LIST = "REMOVE_TO_POPULATION_LIST";
